server:
  port: 8081

spring:
  profiles:
    active: cookie_route

# After Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://httpbin.org:80/get
          predicates:
            - After=2020-01-20T17:42:47.789-07:00[America/Denver]   # 请求时间在此时间之后，则会被路由至指定URL
  profiles: after_route

# Header Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: http://httpbin.org:80/get
          predicates:
            - Header=X-Request-Id, \d+    # 当请求的Header中有X-Request-Id的Header名，且Header值为数字时，则会被路由至指定URL
  profiles: header_route

# Cookie Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://httpbin.org:80/get
          predicates:
            - Cookie=name, liuqi
  profiles: cookie_route

# Host Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://httpbin.org:80/get
          predicates:
            - Host=**.baidu.com
  profiles: host_route

# Method Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: http://httpbin.org:80/get
          predicates:
            - Method=GET
  profiles: method_route

# Path Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://httpbin.org:80/get
          predicates:
            - Path=/foo/{segment}
  profiles: path_route

# Query Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: http://httpbin.org:80/get
          predicates:
            - Query=page, 1
  profiles: query_route
